lexik_jwt_authentication:
    secret_key: '/var/www/html/airbnb-clone/config/jwt/private.pem'
    public_key: '/var/www/html/airbnb-clone/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
